# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MAKEFILE                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: filippomartinoneri <filippomartinoneri@    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/24 16:39:12 by fneri             #+#    #+#              #
#    Updated: 2024/01/26 11:49:19 by filippomart      ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = push_swap
CC = cc
CFLAGS = -Wall -Wextra -Werror
RM = rm -f

SRCS = mainfile.c \
	push_swap.c \
	operation_push.c \
	operation_reverse_rotate.c \
	operation_rotate.c \
	operation_swap.c
				
OBJS = $(SRCS:.c=.o)

LIBFT =	../libft_extended/libft.a
PRINTF = ../ft_printf/libftprintf.a

all: $(NAME)

$(NAME): $(OBJS)
	$(CC) $(CFLAGS) -o $(NAME) $(OBJS) $(LIBFT) $(PRINTF)

$(OBJS): $(SRCS)
	$(CC) $(CFLAGS) -c $(SRCS)

clean:
	$(MAKE) clean -C libft_extended
	$(MAKE) clean -C ft_printf
	$(RM) $(OBJS)

fclean: clean
	$(MAKE) fclean -C libft_extended
	$(MAKE) fclean -C ft_printf
	$(RM) $(NAME)

re: fclean all


.PHONY:	all clean fclean re