# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MAKEFILE                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fneri <fneri@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/24 16:39:12 by fneri             #+#    #+#              #
#    Updated: 2024/01/24 16:43:54 by fneri            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = gcc

RM = rm -f

CFLAGS = -Wall -Wextra -Werror

NAME = push_swap

SRC = main.c /
	push_swap.c /
	operation_push.c /
	operation_reverse_rotate.c /
	operation_rotate.c /
	operation_swap.c
				

LIBFT =	libft/libft.a

OBJ = $(SRC:.c=.o)


$(NAME): $(OBJ)
	make -C ./libft
	$(CC) $(CFLAGS) -o $(NAME) $(OBJ) $(LIBFT)

all: $(NAME)

clean:
	make clean -C libft
	${RM} $(OBJ) $(OBJ_BONUS)

fclean:	clean
	make fclean -C libft
	${RM} $(NAME) $(NAME_BONUS) ${OBJ} $(OBJ_BONUS)

re:	fclean bonus

bonus:	all $(OBJ_BONUS)
	$(CC) $(CFLAGS) -o $(NAME_BONUS) $(OBJ_BONUS) $(LIBFT)


.PHONY:	all clean fclean re